name: first composite action to test

on: 
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: my composite action
        uses: ./.github/actions/composite-cache-deps
        with:
          your-name: 'Rakesh Gorre'
  second-job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: echo 'I see you've recived the hello, glad to meet you
